[SubroutineCall.parser]
production = [
    "@Identifier",
    "bracket.l_parentheses",
    "@ArgumentList?",
    "bracket.r_parentheses",
    "symbol.base.semicolon",
]
end_case = [
    "newline",
]

[SubroutineCall.parser.node]
callee = "$1"
args = "$3"

[SubroutineCall.renderer.layout]
line = [
    { ref = "callee" },
    "(",
    { ref = "args" },
    ")",
    ";",
]

[SubroutineCall.structure]
is_statement = true

[NullStmt.parser]
production = [
    "symbol.base.semicolon",
]
end_case = [
    "newline",
]

[NullStmt.parser.node]

[NullStmt.renderer]
layout = ";"

[NullStmt.structure]
is_statement = true

[GenerateBlock.parser]
bound = { start = "keyword.generate", end = "keyword.endgenerate" }
production = []
end_case = [
    "keyword.endgenerate",
    "newline",
]

[GenerateBlock.parser.node]

[GenerateBlock.renderer]
head = "generate"

[GenerateBlock.renderer.body]
indent = true
role = "flatten"

[GenerateBlock.renderer.tail]
text = "endgenerate"
break = 2

[GenerateBlock.structure]
is_block = true
is_statement = true
