# ============================================================================
# Verilog 语法规则 — 顶层结构与块
# ============================================================================

[Root]

[Root.parser]
block_start = ""
block_end = ""

[Root.renderer]
layout = { join = "\n" }


[Block]
[Block.parser]
block_start = "space.indent"
block_end = "space.dedent"

[BeginEnd]

[BeginEnd.parser]
production = ["keyword.begin", "@Block", "keyword.end"]
end_case = ["keyword.end"]
[BeginEnd.parser.node]
body = "$2"

[BeginEnd.renderer]
body = { indent = true, role = "flatten" }
head = "begin"
tail = { text = "end", break = 1 }

