# ============================================================================
# Verilog 语法规则 — 模块声明
# ============================================================================

[ModuleDecl]
head = { line = [
    "module ",
    { ref = "module_name" },
    { opt = { group = [
        " #(",
        { ref = "params" }, # 这里不再有额外的 soft
        { soft = true },    # 右括号前的软换行
        ")",
    ] } },
    { opt = { group = [
        "(",
        { ref = "ports" }, # 同样没有额外 soft
        { soft = true },   # 右括号前的软换行
        ");",
    ] } },
] }


body = { indent = true, source = "body" }
tail = "endmodule"
production = [
    "keyword.module",
    "id",
    "@ParameterList?",
    "bracket.l_parentheses",
    "@PortList?",
    "bracket.r_parentheses",
    "symbol.base.semicolon",
    "@Block",
    "keyword.endmodule",
]
end_case = ["keyword.endmodule"]
scope_open = true
scope_name_attr = "module_name"
scope_kind = "module"

[ModuleDecl.node]
module_name = "$2"
params = "$3"
ports = "$5"
body = "$8"

[ParameterList]
layout = { join = ", ", first_soft = true, nest = 1 }
production = [
    "symbol.base.pound",
    "bracket.l_parentheses",
    "@ParamDecl",
    "(symbol.base.comma,@ParamDecl)*",
    "bracket.r_parentheses",
]
[ParameterList.node]
first = "$3"
rest = "$4"

[ParamDecl]
layout = { line = [
    "parameter ",
    { ref = "param_name" },
    " = ",
    { ref = "value" },
] }
production = ["keyword.parameter", "id", "symbol.base.equal", "@Expression"]
end_case = ["symbol.base.comma", "bracket.r_parentheses", "newline"]
symbol_kind = "parameter"
symbol_name = "param_name"
[ParamDecl.node]
param_name = "$2"
value = "$4"
