# ============================================================================
# Verilog 语法规则 — 端口与声明
# ============================================================================

[PortList]
production = ["@PortDecl", "(symbol.base.comma,@PortDecl)*"]
template = "{{#first}}{{.}}{{/first}}{{#rest}} {{.}}{{/rest}}"
[PortList.node]
first = "$1"
rest = "$2"

[PortDecl]
production = [
    "keyword.input|keyword.output|keyword.inout",
    "@OptType?",
    "@Range?",
    "id",
]
end_case = [
    "symbol.base.comma",
    "bracket.r_parentheses",
    "newline",
    "space.dedent",
]
template = "{{ direction }}{{?port_type}} {{ port_type }}{{/port_type}}{{?range}} [{{range}}]{{/range}} {{ port_name }}"
[PortDecl.node]
direction = "$1"
port_type = "$2"
range = "$3"
port_name = "$4"

[OptType]
production = ["keyword.wire|keyword.reg"]
inline = true
template = "{{ type_desc }}"
[OptType.node]
type_desc = "$1"

[Range]
production = [
    "bracket.l_square_bracket",
    "@Expression",
    "symbol.base.colon",
    "@Expression",
    "bracket.r_square_bracket",
]
template = "{{ msb }}:{{ lsb }}"
[Range.node]
msb = "$2"
lsb = "$4"

[WireDecl]
production = ["keyword.wire", "@Range?", "id", "symbol.base.semicolon"]
end_case = ["newline"]
template = "    wire{{?range}} [{{range}}]{{/range}} {{ wire_name }};"
[WireDecl.node]
wire_type = "$1"
range = "$2"
wire_name = "$3"

[RegDecl]
production = ["keyword.reg", "@Range?", "id", "symbol.base.semicolon"]
end_case = ["newline"]
template = "    reg{{?range}} [{{range}}]{{/range}} {{ reg_name }};"
[RegDecl.node]
reg_type = "$1"
range = "$2"
reg_name = "$3"

[LocalParamDecl]
production = [
    "keyword.localparam",
    "@LocalParamItemList",
    "symbol.base.semicolon",
]
end_case = ["newline"]
template = """    localparam {{#items}}{{?@first}}{{.}},{{/@first}}{{!@first}}
        {{.}}{{!@last}},{{/@last}}{{/@first}}{{/items}};"""
[LocalParamDecl.node]
items = "$2"

[LocalParamItemList]
production = ["@LocalParamItem", "(symbol.base.comma,@LocalParamItem)*"]
[LocalParamItemList.node]
first = "$1"
rest = "$2"

[LocalParamItem]
production = ["id", "symbol.base.equal", "@Expression"]
template = "{{ param_name }} = {{ value }}"
[LocalParamItem.node]
param_name = "$1"
value = "$3"
