# ============================================================================
# 顶层和块结构
# ============================================================================

[Root]
template = """{{#child}}{{.}}
{{/child}}"""

[Block]
template = """{{#child}}{{.}}
{{/child}}"""
