# ============================================================================
# 变量声明与赋值
# ============================================================================

[VarInit]
template = "\t{{ var_name }}: {{ type }} = {{ value }}"

[VarDecl]
template = "\t{{ var_name }}: {{ type }}"

[AssignStmt]
template = "\t{{ var_name }} = {{ value }}"
