# ============================================================================
# 导入语句
# ============================================================================

[ImportStatement]
template = "\timport {{ module }}{{?alias}} as {{ alias }}{{/alias}}"

[FromImport]
template = "\tfrom {{ module }} import {{ name }}{{?alias}} as {{ alias }}{{/alias}}"
