# ============================================================================
# 调用与传参
# ============================================================================

[CallStmt]
template = "\t{{ call }}"

[Call]
template = "{{ callable_name }}({{ args }})"

[Arguments]
template = "{{ first }}{{#rest}}, {{.}}{{/rest}}"
