# ============================================================================
# 字面量
# ============================================================================

[Number]
template = "{{ value }}"

[Bool]
template = "{{ value }}"

[String]
template = "\"{{ value }}\""

[NoneLiteral]
template = "none"
