# ============================================================================
# 标识符
# ============================================================================

[id]
template = "{{ value }}"

[Identifier]
template = "{{ content }}"
