// Generated by PyV Compiler

module led_blinker (
	input wire clk["symbol.base.comma", "PortDecl"]["symbol.base.comma", "PortDecl"]
);
		reg [31:0] counter;
	always @(posedge clk ["symbol.extend.logic_or", "EdgeSense"]) begin
	if (!rst_n) begin
		counter <= 32'd0;
		led <= 1'b0;
	end
	else if (counter == 32'd1000) begin
		counter <= 32'd0;
		led <= ~led;
	end
	else begin
		counter <= counter + 32'd1;
	end
	end

endmodule
