#!/usr/bin/env python3
"""
Regression test runner – schedules run_pipeline.py for each test case.
Does not re-implement the pipeline, instead imports and calls run_pipeline_on_source.

Usage:
    python run_all_tests.py                    # all tests
    python run_all_tests.py normal             # normal group only
    python run_all_tests.py errors             # errors group only
    python run_all_tests.py normal counter     # normal/ref_counter only
    python run_all_tests.py -v                 # verbose output
    python run_all_tests.py --json             # JSON report
    python run_all_tests.py --expand-macros    # enable macro expansion
    python run_all_tests.py --inline-comments  # enable inline comment injection
"""

import sys
import os
import json
import time
import io
from typing import List, Tuple, Dict, Any
from core.define import DEFAULT_EXT_DIRS

# Force stdout to UTF-8
sys.stdout = open(sys.stdout.fileno(), "w", encoding="utf-8", closefd=False)

# Add project root to path for importing pipeline
project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if project_root not in sys.path:
    sys.path.insert(0, project_root)


def discover_tests(
    base_dir: str, group_filter: str | None = None, name_filter: str | None = None
) -> List[Tuple[str, str, str]]:
    """Discover test files. Returns list of (name, full_path, group)."""
    tests_dir = os.path.join(base_dir, "tests")
    cases = []
    groups = [group_filter] if group_filter else ["normal", "errors"]
    for group in groups:
        ref_dir = os.path.join(tests_dir, group, "ref")
        if not os.path.isdir(ref_dir):
            continue
        for f in sorted(os.listdir(ref_dir)):
            if not f.endswith(".v") or f.startswith("_"):
                continue
            name = f.replace(".v", "")
            if name_filter and name != name_filter:
                continue
            cases.append((name, os.path.join(ref_dir, f), group))
    return cases


def run_all(
    verbose: bool = False,
    json_out: bool = False,
    inline_comments: bool = False,
    expand_macros: bool = False,
    no_semantic: bool = False,
    enable_diff: bool = False,
    group_filter: str | None = None,
    name_filter: str | None = None,
) -> bool:
    """Run all tests and return True if all pass."""
    base_dir = os.path.dirname(os.path.abspath(__file__))

    # Import the core pipeline function (shared context initializes on first call)
    from run_pipeline import run_pipeline_on_source

    cases = discover_tests(base_dir, group_filter, name_filter)
    if not cases:
        print("[error] no test cases found", file=sys.stderr)
        return False

    results = []
    total_ok = 0
    total_err = 0
    total_fail = 0
    t_start = time.time()

    for name, path, group in cases:
        with open(path, "r", encoding="utf-8") as f:
            source = f.read()

        out_dir = os.path.join(base_dir, "tests", group)

        # 日志抑制
        old_stdout = sys.stdout
        old_stderr = sys.stderr
        if not verbose:
            sys.stdout = io.StringIO()
            sys.stderr = io.StringIO()
        try:
            result: Dict[str, Any] = run_pipeline_on_source(
                source=source,
                input_path=path,
                out_dir=out_dir,
                expand_macros=expand_macros,
                inline_comments=inline_comments,
                debug=False,
                quiet=True,
                analyzer_enabled=not no_semantic,
                transform_enabled=not no_semantic,
                renderer_enabled=True,
                stage=None,
                ext_dirs=DEFAULT_EXT_DIRS,
            )
        finally:
            if not verbose:
                sys.stdout = old_stdout
                sys.stderr = old_stderr

        success = result["success"]
        err_msg = result["error"] or ""

# ---- 生成文件与参考文件的 diff 检查（默认关闭）----
        diff_ok = True
        diff_lines: list[str] = []
        if enable_diff and group == "normal":
            base_name = name.replace("ref_", "", 1) if name.startswith("ref_") else name
            gen_path = os.path.join(out_dir, "gen", f"gen_{base_name}.v")
            if os.path.exists(gen_path):
                with open(gen_path, "r", encoding="utf-8") as f:
                    gen_content = f.read()
                ref_content = source

                # 去头 + 去注释 + 去空白比较：忽略所有格式差异
                def strip_header(text: str) -> str:
                    lines = []
                    for line in text.split("\n"):
                        if line.startswith("// Generated by"):
                            continue
                        # 去行内注释
                        ci = line.find("//")
                        if ci >= 0:
                            line = line[:ci]
                        lines.append(line)
                    return "\n".join(lines)

                ref_flat = "".join(strip_header(ref_content).split())
                gen_flat = "".join(strip_header(gen_content).split())
                diff_ok = ref_flat == gen_flat

        # 判定测试结果
        if group == "errors":
            passed = not success
        else:
            passed = success and diff_ok

        if passed:
            if group == "errors":
                total_err += 1
                status = "ERR"
            else:
                total_ok += 1
                status = "OK"
        else:
            total_fail += 1
            status = "FAIL"

        results.append((name, passed, status, err_msg[:60]))

        if not passed and diff_lines and verbose:
            for line in diff_lines[:20]:
                print(f"      {line}")
        print(f"  {name:25s} {status:5s} {err_msg[:40]}")

    elapsed = time.time() - t_start
    total = total_ok + total_err + total_fail
    print(f"\n{'=' * 40}")
    print(
        f"\n  Total: {total}  OK: {total_ok}  ERR: {total_err}  FAIL: {total_fail}  Time: {elapsed:.1f}s"
    )

    if json_out:
        report = {
            "total": total,
            "ok": total_ok,
            "err": total_err,
            "fail": total_fail,
            "elapsed": round(elapsed, 2),
            "cases": [
                {"name": n, "ok": ok, "status": status, "error": err}
                for n, ok, status, err in results
            ],
        }
        json_path = os.path.join(base_dir, "test_report.json")
        with open(json_path, "w", encoding="utf-8") as f:
            json.dump(report, f, indent=2, ensure_ascii=False)
        print(f"  Report saved: {json_path}")

    return total_fail == 0


if __name__ == "__main__":
    verbose = "-v" in sys.argv or "--verbose" in sys.argv
    json_out = "--json" in sys.argv
    inline_comments = "--inline-comments" in sys.argv
    expand_macros = "--expand-macros" in sys.argv
    no_semantic = "--no-semantic" in sys.argv
    enable_diff = "--diff" in sys.argv

    pos_args = [a for a in sys.argv[1:] if not a.startswith("-")]
    group_filter = pos_args[0] if len(pos_args) >= 1 else None
    name_filter = pos_args[1] if len(pos_args) >= 2 else None

    if group_filter and group_filter not in ("normal", "errors"):
        print(f"[error] unknown group: {group_filter} (expected normal|errors)")
        sys.exit(1)
    if name_filter:
        name_filter = f"ref_{name_filter}".replace(".v", "")

    ok = run_all(
        verbose=verbose,
        json_out=json_out,
        inline_comments=inline_comments,
        expand_macros=expand_macros,
        no_semantic=no_semantic,
        enable_diff=enable_diff,
        group_filter=group_filter,
        name_filter=name_filter,
    )
    sys.exit(0 if ok else 1)
