[Root.parser.structure]
is_block = true

[Root.renderer.layout]
join = "\n"

[Root.structure]
is_block = true

[Comment.parser]
production = [
    "comment",
]
end_case = []

[Comment.parser.node]
value = "$1.value"

[Comment.renderer.layout]
ref = "value"

[ModuleBlock.parser]
end_case = [
    "keyword.endmodule",
]

[ModuleBlock.parser.structure]
is_block = true

[ModuleBlock.renderer.body]
indent = true
role = "flatten"

[ModuleBlock.structure]
is_block = true

[ProcBlock.parser]
end_case = [
    "keyword.end",
]

[ProcBlock.parser.structure]
is_block = true

[ProcBlock.renderer.body]
indent = true
role = "flatten"

[ProcBlock.structure]
is_block = true

[TaskBlock.parser]
end_case = [
    "keyword.endfunction",
    "keyword.endtask",
]

[TaskBlock.parser.structure]
is_block = true

[TaskBlock.renderer.body]
indent = true
role = "flatten"

[TaskBlock.structure]
is_block = true

[BeginEnd.parser]
production = [
    "keyword.begin",
    "@BlockLabel?",
    "@ProcBlock",
    "keyword.end",
]
end_case = [
    "keyword.end",
    "newline",
]

[BeginEnd.parser.node]
label = "$2"
body = "$3"

[BeginEnd.renderer.head]
line = [
    "begin",
    { opt = { group = [
    ": ",
    { ref = "label" },
] } },
]

[BeginEnd.renderer.body]
indent = true
source = "body"

[BeginEnd.renderer.tail]
text = "end"
break = 1

[BeginEnd.structure]
is_statement = true

[BlockLabel.parser]
production = [
    "symbol.base.colon",
    "@Identifier",
]
inline = true

[BlockLabel.parser.node]
name = "$2"

[BlockLabel.renderer.layout]
line = [
    ": ",
    { ref = "name" },
]
