[AlwaysBlock.parser]
production = [
    "keyword.always",
    "symbol.base.at",
    "bracket.l_parentheses",
    "@SensitivityList",
    "bracket.r_parentheses",
    "@Statement",
]
end_case = [
    "newline",
    "keyword.end",
]

[AlwaysBlock.parser.node]
sensitivity = "$4"
body = "$6"

[AlwaysBlock.renderer.layout]
line = [
    "always @(",
    { ref = "sensitivity" },
    ") ",
    { ref = "body" },
]

[AlwaysBlock.renderer.body]
role = "direct"

[AlwaysBlock.renderer.override.BeginEnd]
tail_break = 2

[AlwaysBlock.structure]
is_statement = true

[SensitivityList.parser]
production = [
    "@EdgeSense|symbol.base.multiple",
    "(symbol.extend.logic_or,@EdgeSense)*",
]

[SensitivityList.parser.node]
items = [
    "$1",
    "$2.items[*].sub_node[1]",
]

[SensitivityList.renderer.layout]
join = " or "
items = "items"

[EdgeSense.parser]
production = [
    "keyword.posedge|keyword.negedge",
    "@Identifier",
]

[EdgeSense.parser.node]
edge = "$1"
signal = "$2"

[EdgeSense.renderer.layout]
line = [
    { ref = "edge" },
    " ",
    { ref = "signal" },
]
