[MacroResetall.parser]
production = [
    "macro.resetall",
]
end_case = [
    "newline",
]

[MacroResetall.parser.structure]
is_statement = true

[MacroResetall.structure]
is_statement = true

[MacroCelldefine.parser]
production = [
    "macro.celldefine",
]
end_case = [
    "newline",
]

[MacroCelldefine.parser.structure]
is_statement = true

[MacroCelldefine.structure]
is_statement = true

[MacroEndCellDefine.parser]
production = [
    "macro.endcelldefine",
]
end_case = [
    "newline",
]

[MacroEndCellDefine.parser.structure]
is_statement = true

[MacroEndCellDefine.structure]
is_statement = true

[MacroElse.parser]
production = [
    "macro.else",
]
end_case = [
    "newline",
]

[MacroElse.parser.structure]
is_statement = true

[MacroElse.structure]
is_statement = true

[MacroEndif.parser]
production = [
    "macro.endif",
]
end_case = [
    "newline",
]

[MacroEndif.parser.structure]
is_statement = true

[MacroEndif.structure]
is_statement = true

[MacroEndKeywords.parser]
production = [
    "macro.end_keywords",
]
end_case = [
    "newline",
]

[MacroEndKeywords.parser.structure]
is_statement = true

[MacroEndKeywords.structure]
is_statement = true

[MacroNoUnconnectedDrive.parser]
production = [
    "macro.nounconnected_drive",
]
end_case = [
    "newline",
]

[MacroNoUnconnectedDrive.parser.structure]
is_statement = true

[MacroNoUnconnectedDrive.structure]
is_statement = true

[MacroUndef.parser]
production = [
    "macro.undef",
    "@Identifier",
]
end_case = [
    "newline",
]

[MacroUndef.parser.structure]
is_statement = true

[MacroUndef.structure]
is_statement = true

[MacroIfdef.parser]
production = [
    "macro.ifdef",
    "@Identifier",
]
end_case = [
    "newline",
]

[MacroIfdef.parser.structure]
is_statement = true

[MacroIfdef.structure]
is_statement = true

[MacroIfndef.parser]
production = [
    "macro.ifndef",
    "@Identifier",
]
end_case = [
    "newline",
]

[MacroIfndef.parser.structure]
is_statement = true

[MacroIfndef.structure]
is_statement = true

[MacroUnconnectedDrive.parser]
production = [
    "macro.unconnected_drive",
    "@Identifier",
]
end_case = [
    "newline",
]

[MacroUnconnectedDrive.parser.structure]
is_statement = true

[MacroUnconnectedDrive.structure]
is_statement = true

[MacroDefaultNettype.parser]
production = [
    "macro.default_nettype",
]
end_case = [
    "newline",
]

[MacroDefaultNettype.parser.structure]
is_statement = true

[MacroDefaultNettype.structure]
is_statement = true

[MacroInclude.parser]
production = [
    "macro.include",
    "literal.string",
]
end_case = [
    "newline",
]

[MacroInclude.parser.structure]
is_statement = true

[MacroInclude.structure]
is_statement = true

[MacroBeginKeywords.parser]
production = [
    "macro.begin_keywords",
    "literal.string",
]
end_case = [
    "newline",
]

[MacroBeginKeywords.parser.structure]
is_statement = true

[MacroBeginKeywords.structure]
is_statement = true

[MacroLineDirective.parser]
production = [
    "macro.line",
    "literal.number",
    "literal.string",
]
end_case = [
    "newline",
]

[MacroLineDirective.parser.structure]
is_statement = true

[MacroLineDirective.structure]
is_statement = true

[MacroTimescale.parser]
production = [
    "macro.timescale",
    "literal.number",
    "@Identifier",
    "symbol.base.div",
    "literal.number",
    "@Identifier",
]
end_case = [
    "newline",
]

[MacroTimescale.parser.structure]
is_statement = true

[MacroTimescale.structure]
is_statement = true

[MacroElsif.parser]
production = [
    "macro.elsif",
    "@PrimaryExpr",
]
end_case = [
    "newline",
]

[MacroElsif.parser.structure]
is_statement = true

[MacroElsif.structure]
is_statement = true

[MacroPragma.parser]
production = [
    "macro.pragma",
    "@Identifier",
]
end_case = [
    "newline",
]

[MacroPragma.parser.structure]
is_statement = true

[MacroPragma.structure]
is_statement = true

[MacroValue.parser]
production = [
    "@Expression",
]
end_case = [
    "newline",
]

[MacroDefine.parser]
production = [
    "macro.define",
    "@Identifier",
    "@MacroValue?",
]
end_case = [
    "newline",
]

[MacroDefine.parser.structure]
is_statement = true

[MacroDefine.parser.node]
macro_name = "$1"
body = "$2"

[MacroDefine.structure]
is_statement = true

[MacroCall.parser]
production = [
    "macro.call",
]
end_case = []
