[PortList.parser]
production = [
    "@AnsiPortDecl",
    "(symbol.base.comma,@AnsiPortDecl)*",
]

[PortList.parser.node]
items = [
    "$1",
    "$2.items[*].sub_node[1]",
]

[PortList.renderer.layout]
join = ", "
first_soft = true
nest = 1
items = "items"

[TaskPortList.parser]
production = [
    "@TaskAnsiPortDecl",
    "(symbol.base.comma,@TaskAnsiPortDecl)*",
]

[TaskPortList.parser.node]
items = [
    "$1",
    "$2.items[*].sub_node[1]",
]

[TaskPortList.renderer.layout]
join = ", "
first_soft = true
nest = 1
items = "items"

[TaskAnsiPortDecl.parser]
production = [
    "@TaskAnsiInputDecl|@AnsiOutputDecl|@AnsiInoutDecl",
]
inline = true

[TaskAnsiPortDecl.parser.node]
decl = "$1"

[TaskAnsiPortDecl.renderer.layout]
ref = "decl"

[TaskAnsiInputDecl.parser]
production = [
    "keyword.input",
    "@PortTail",
]
end_case = [
    "symbol.base.comma",
    "bracket.r_parentheses",
    "newline",
]

[TaskAnsiInputDecl.parser.structure]
is_statement = false

[TaskAnsiInputDecl.parser.node]
direction = "input"
port_type = "$2.port_type"
is_signed = "$2.is_signed"
packed_range = "$2.packed_range"
items = "$2.items"

[TaskAnsiInputDecl.analyzer.symbol]
kind = "port"
name_attr = "items.name"

[TaskAnsiInputDecl.renderer.layout]
line = [
    "input",
    { opt = { group = [
    " ",
    { ref = "port_type" },
] } },
    { opt = { group = [
    " ",
    { ref = "is_signed" },
] } },
    { opt = { group = [
    " [",
    { ref = "packed_range" },
    "]",
] } },
    " ",
    { ref = "items" },
]

[AnsiPortDecl.parser]
production = [
    "@AnsiInputDecl|@AnsiOutputDecl|@AnsiInoutDecl",
]
inline = true

[AnsiPortDecl.parser.node]
decl = "$1"

[AnsiPortDecl.renderer.layout]
ref = "decl"

[DirSpec.parser]
production = [
    "keyword.input|keyword.output|keyword.inout",
]

[DirSpec.parser.node]
direction = "$1"

[DirSpec.renderer.layout]
ref = "direction"

[PortDeclPrefix.parser]
production = [
    "@DirSpec",
    "@TypeSpec",
]

[PortDeclPrefix.parser.node]
direction = "$1.direction"
port_type = "$2.port_type"
is_signed = "$2.is_signed"
packed_range = "$2.packed_range"

[[PortDeclPrefix.renderer.layout.line]]
ref = "direction"

[[PortDeclPrefix.renderer.layout.line]]

[PortDeclPrefix.renderer.layout.line.opt]
group = [
    " ",
    { ref = "port_type" },
]

[[PortDeclPrefix.renderer.layout.line]]

[PortDeclPrefix.renderer.layout.line.opt]
group = [
    " ",
    { ref = "is_signed" },
]

[[PortDeclPrefix.renderer.layout.line]]

[PortDeclPrefix.renderer.layout.line.opt]
group = [
    " [",
    { ref = "packed_range" },
    "]",
]

[AnsiInputDecl.parser]
production = [
    "keyword.input",
    "@TypeSpecNoReg",
    "@DeclaratorList",
]
end_case = [
    "symbol.base.comma",
    "bracket.r_parentheses",
    "symbol.base.semicolon",
    "newline",
]

[AnsiInputDecl.parser.structure]
is_statement = false

[AnsiInputDecl.parser.node]
direction = "input"
port_type = "$2.port_type"
is_signed = "$2.is_signed"
packed_range = "$2.packed_range"
items = "$3"

[AnsiInputDecl.analyzer.symbol]
kind = "port"
name_attr = "items.name"

[AnsiInputDecl.renderer.layout]
line = [
    { ref = "direction" },
    { opt = { group = [
    " ",
    { ref = "port_type" },
] } },
    { opt = { group = [
    " ",
    { ref = "is_signed" },
] } },
    { opt = { group = [
    " [",
    { ref = "packed_range" },
    "]",
] } },
    " ",
    { ref = "items" },
]

[AnsiOutputDecl.parser]
production = [
    "keyword.output",
    "@TypeSpec",
    "@DeclaratorList",
]
end_case = [
    "symbol.base.comma",
    "bracket.r_parentheses",
    "symbol.base.semicolon",
    "newline",
]

[AnsiOutputDecl.parser.structure]
is_statement = false

[AnsiOutputDecl.parser.node]
direction = "output"
port_type = "$2.port_type"
is_signed = "$2.is_signed"
packed_range = "$2.packed_range"
items = "$3"

[AnsiOutputDecl.analyzer.symbol]
kind = "port"
name_attr = "items.name"

[AnsiOutputDecl.renderer.layout]
line = [
    { ref = "direction" },
    { opt = { group = [
    " ",
    { ref = "port_type" },
] } },
    { opt = { group = [
    " ",
    { ref = "is_signed" },
] } },
    { opt = { group = [
    " [",
    { ref = "packed_range" },
    "]",
] } },
    " ",
    { ref = "items" },
]

[AnsiInoutDecl.parser]
production = [
    "keyword.inout",
    "@TypeSpecNoReg",
    "@DeclaratorList",
]
end_case = [
    "symbol.base.comma",
    "bracket.r_parentheses",
    "symbol.base.semicolon",
    "newline",
]

[AnsiInoutDecl.parser.structure]
is_statement = false

[AnsiInoutDecl.parser.node]
direction = "inout"
port_type = "$2.port_type"
is_signed = "$2.is_signed"
packed_range = "$2.packed_range"
items = "$3"

[AnsiInoutDecl.analyzer.symbol]
kind = "port"
name_attr = "items.name"

[AnsiInoutDecl.renderer.layout]
line = [
    { ref = "direction" },
    { opt = { group = [
    " ",
    { ref = "port_type" },
] } },
    { opt = { group = [
    " ",
    { ref = "is_signed" },
] } },
    { opt = { group = [
    " [",
    { ref = "packed_range" },
    "]",
] } },
    " ",
    { ref = "items" },
]
