# ============================================================================
# Verilog 语法规则 — 端口与声明（组合复用）
# ============================================================================

[WireDecl]
[WireDecl.parser]
production = [
    "keyword.wire",
    "keyword.signed?",
    "@Range?",
    "@DeclaratorList",
    "symbol.base.semicolon",
]
end_case = ["newline"]
[WireDecl.parser.node]
wire_type = "$1"
is_signed = "$2"
packed_range = "$3"
items = "$4"
[WireDecl.analyzer]
symbol = { kind = "wire", name_attr = "items.name" }
[WireDecl.renderer]
layout = { line = [
    "wire",
    { opt = { group = [" ", { ref = "is_signed" }] } },
    { opt = { group = [
        " [",
        { ref = "packed_range" },
        "]",
    ] } },
    " ",
    { ref = "items" },
    ";",
] }

[RegDecl]
[RegDecl.parser]
production = [
    "keyword.reg",
    "keyword.signed?",
    "@Range?",
    "@DeclaratorList",
    "symbol.base.semicolon",
]
end_case = ["newline"]
[RegDecl.parser.node]
reg_type = "$1"
is_signed = "$2"
packed_range = "$3"
items = "$4"
[RegDecl.analyzer]
symbol = { kind = "reg", name_attr = "items.name" }
[RegDecl.renderer]
layout = { line = [
    "reg",
    { opt = { group = [" ", { ref = "is_signed" }] } },
    { opt = { group = [
        " [",
        { ref = "packed_range" },
        "]",
    ] } },
    " ",
    { ref = "items" },
    ";",
] }

[IntegerDecl]
[IntegerDecl.parser]
production = ["keyword.integer", "@DeclaratorList", "symbol.base.semicolon"]
end_case = ["newline"]
[IntegerDecl.parser.node]
items = "$2"
[IntegerDecl.analyzer]
symbol = { kind = "integer", name_attr = "items.name" }
[IntegerDecl.renderer]
layout = { line = ["integer ", { ref = "items" }, ";"] }

