# ============================================================================
# 函数调用与参数
# ============================================================================

[Arguments]
production = ["@Expression", "(symbol.base.comma,@Expression)*"]
[Arguments.node]
first = "$1"
rest = "$2"

[Call]
production = [
    "id",
    "bracket.l_parentheses",
    "@Arguments?",
    "bracket.r_parentheses",
]
[Call.node]
callable_name = "$1"
args = "$3"
