# ============================================================================
# 类型系统
# ============================================================================

[ListType]
production = ["bracket.l_square_bracket", "@Type", "bracket.r_square_bracket"]
[ListType.node]
elem_type = "$2"

[OptionalType]
production = ["symbol.base.question_mark", "@Type"]
[OptionalType.node]
inner = "$2"

[Type]
production = ["id|@ListType|@OptionalType"]
inline = true
[Type.node]
type_desc = "$1"
