# ============================================================================
# 字面量表达式（列表、初始化）
# ============================================================================

[ListLiteral]
production = [
    "bracket.l_square_bracket",
    "(@Initializer,symbol.base.comma)*",
    "bracket.r_square_bracket",
]
[ListLiteral.node]
elements = "$2"

[Initializer]
production = ["@ListLiteral|@Call|@Expression"]
inline = true
[Initializer.node]
value = "$1"
