# ============================================================================
# 语句（Statements）
# ============================================================================

[VarDecl]
production = ["id", "symbol.base.colon", "@Type"]
end_case = ["newline"]
[VarDecl.node]
var_name = "$1"
type = "$3"

[VarInit]
production = [
    "id",
    "symbol.base.colon",
    "@Type",
    "symbol.base.equal",
    "@Initializer",
]
end_case = ["newline"]
[VarInit.node]
var_name = "$1"
type = "$3"
value = "$5"

[AssignStmt]
production = ["id", "symbol.base.equal", "@Initializer"]
end_case = ["newline"]
[AssignStmt.node]
var_name = "$1"
value = "$3"

[IdList]
production = ["id+"]
end_case = ["newline"]
[IdList.node]
items = "$1"

[CallStmt]
production = ["@Call"]
end_case = ["newline"]
[CallStmt.node]
call = "$1"

[PassStmt]
production = ["keyword.pass"]
end_case = ["newline"]
[PassStmt.node]

[BreakStmt]
production = ["keyword.break"]
end_case = ["newline"]
[BreakStmt.node]

[ContinueStmt]
production = ["keyword.continue"]
end_case = ["newline"]
[ContinueStmt.node]
