# ============================================================================
# 块结构（缩进块、根块）
# ============================================================================

[Root]
block_start = ""
block_end = ""

[Block]
block_start = "space.indent"
block_end = "space.dedent"
