power = 13
multi = 12
div = 12
mod = 12
add = 11
sub = 11
r_shift = 10
l_shift = 10
not = 9
and = 8
xnor = 7
or = 6
bigger = 5
lesser = 5
bigger_equal = 5
lesser_equal = 5
not_equal = 4
add_equal = 4
sub_equal = 4
logic_not = 3
logic_add = 2
logic_or = 1
