[Constant]
production = ["literal.number"]
[Constant.node]
value = "$1"


[Variable]
production = ["id"]
[Variable.node]
name = "$1"


[VarDef]
production = ["id", "[id]", "symbol.base.equal", "@Expression"]
[VarDef.node]
name = "$1"
type = "$2"
value = "$4"

# Parenthesized expressions
[ParenthesizedExpr]
production = ["bracket.l_parentheses", "@Expression", "bracket.r_parentheses"]
[ParenthesizedExpr.node]
expr = "$2"

# Primary expressions (atoms)
[PrimaryExpr]
production = ["@Constant|@Variable|@ParenthesizedExpr"]
[PrimaryExpr.node]
value = "$1"

# Multiplicative expressions (*, /)
[MulExpr]
production = ["@PrimaryExpr", "[{@MulExprChain}]"]
[MulExpr.node]
left = "$1"
chain = "$2"

[MulExprChain]
production = ["symbol.base.multiple|symbol.base.div", "@PrimaryExpr"]
[MulExprChain.node]
op = "$1"
right = "$2"

# Additive expressions (+, -)
[AddExpr]
production = ["@MulExpr|@PrimaryExpr", "[{@AddExprChain}]"]
[AddExpr.node]
left = "$1"
chain = "$2"

[AddExprChain]
production = ["symbol.base.add|symbol.base.sub", "@MulExpr|@PrimaryExpr"]
[AddExprChain.node]
op = "$1"
right = "$2"

# Comparison expressions
[CompareExpr]
production = [
    "@AddExpr",
    "symbol.extend.is_equal|symbol.extend.not_equal|symbol.extend.bigger|symbol.extend.lesser|symbol.extend.bigger_equal|symbol.extend.lesser_equal",
    "@AddExpr",
]
[CompareExpr.node]
left = "$1"
op = "$2"
right = "$3"

# Boolean expressions
[BoolExpr]
production = ["@CompareExpr|literal.bool_true|literal.bool_false"]
[BoolExpr.node]
value = "$1"

# Top-level expression
[Expression]
production = ["@AddExpr|@BoolExpr"]
[Expression.node]
expr = "$1"


# Code block
[Block]
production = [
    "bracket.l_curly_bracket",
    "[{@Statement}]",
    "bracket.r_curly_bracket",
]
[Block.node]
statements = "$2"

# Statement
[Statement]
production = ["@Expression|@VarDef|@IfStmt|@WhileStmt"]
[Statement.node]
stmt = "$1"


# If statement
[IfStmt]
production = [
    "keyword.if",
    "bracket.l_parentheses",
    "@BoolExpr",
    "bracket.r_parentheses",
    "@Block",
    "[@ElseStmt]",
]
[IfStmt.node]
condition = "$3"
then_block = "$5"
else_block = "$6"


# Else statement
[ElseStmt]
production = ["keyword.else", "@Block"]
[ElseStmt.node]
block = "$2"

# While statement
[WhileStmt]
production = [
    "keyword.while",
    "bracket.l_parentheses",
    "@BoolExpr",
    "bracket.r_parentheses",
    "@Block",
]
[WhileStmt.node]
condition = "$3"
body = "$5"
