[Constant]
keywords = ["constant", "base"]
production = ["literal.number"]
[Constant.node_info]
name = "constant"
content = "$1"


[Operator]
keywords = ["operator", "base"]
production = [
    "symbol.base.add|symbol.base.sub|symbol.base.multiple|symbol.base.div",
]
[Operator.node_info]
name = "operation"
operator = "$1"



[Variable]
keywords = ["variable", "base"]
production = ["id"]
[Variable.node_info]
_do_not_declare_node = "True"


[OperationExp]
keywords = ["operation_expression"]
production = ["GrammarRule(Operator)", "GrammarRule(Variable|Constant)"]
[OperationExp.node_info]
name = "operation_expression"
operator = "$1"
operand = "$2"


[VariableDef]
keywords = ["variable", "definition"]
production = [
    "id",
    "id",
    "symbol.base.equal",
    "GrammarRule(Constant|Variable|Expression)",
]
[VariableDef.node_info]
name = "$1"
var_type = "$2"
init_value = "$4"
