[space]
blank_space = " "
tab = "\t"

[newline]
newline = "\n"

[comment]
boundary = "#"

[symbol]
[symbol.base]
add = "+"
sub = "-"
multiple = "*"
and = "&"
or = "|"
not = "!"
xnor = "^"
bigger = ">"
lesser = "<"
div = "/"
mod = "%"
equal = "="
dot = "."
comma = ","
colon = ":"
semicolon = ";"
question_mark = "?"
at = "@"
[symbol.extend]
r_shift = ">>"
l_shift = "<<"
point_to = "->"
power = "**"
bigger_equal = ">="
lesser_equal = "<="
is_equal = "=="
not_equal = "!="
add_equal = "+="
sub_equal = "-="
add_one = "++"
sub_one = "--"
double_dot = ".."

[bracket]
l_parentheses = "("
r_parentheses = ")"
l_square_bracket = "["
r_square_bracket = "]"
l_curly_bracket = "{"
r_curly_bracket = "}"
l_angle_bracket = "<"
r_angle_bracket = ">"

[id]
[id.keyword]
# al type
al_ff = "al_ff"
al_comb = "al_comb"
# branch
if = "if"
else = "else"
match = "match"
case = "case"
# import
import = "import"
from = "from"
as = "as"
# loop
for = "for"
while = "while"
break = "break"
continue = "continue"

# param
param = "param"

# port 
input = "input"
output = "output"
inout = "inout"
interface = "interface"

# module
module = "module"

# logic operator
logic_add = "and"
logic_or = "or"
logic_not = "not"
# tag
tag = "tag"
# process
pass = "pass"
# edge
posedge = "posedge"
negedge = "negedge"

[id.id]
id = "[a-z_A-Z][a-z_A-Z0-9]*"

[literal]
string = "(\".*\")|('.*')"
bool_false = "False"
bool_true = "True"
number = "\\d+"
none = "None"

