[ModuleDecl]
template = """module {{ module_name }}{{#params}}{{?@first}} #(
{{/@first}}\t{{.}}{{!@last}},{{/@last}}{{?@last}}
){{/@last}}{{/params}} (
{{#ports}}\t{{.}}{{!@last}},{{/@last}}
{{/ports}});
{{#body}}\t{{.}}
{{/body}}endmodule"""

[ParameterList]
template = "# ({{ first }}{{#rest}} {{.}}{{/rest}})"

[ParamDecl]
template = "parameter {{ param_name }} = {{ value }}"

[PortDecl]
template = "{{ direction }} {{ port_type }} {{ port_name }}"

[OptType]
template = "{{ type_desc }}"