[ModuleDecl]
template = """module {{ module_name }}{{?params}} {{ params }}{{/params}} (
    {{#ports}}
    {{.}}{{/ports}}
);
\t{{ body }}
endmodule"""

[PortList]
template = "{{ elements }}"

[ParameterList]
template = "# ({{ first }}{{#rest}} {{.}}{{/rest}})"

[ParamDecl]
template = "parameter {{ param_name }} = {{ default }}"

[PortDecl]
template = "{{ direction }} {{#port_type}}{{.}} {{/port_type}}{{ port_name }}"

[OptType]
template = "{{ type_desc }}"
