[AlwaysBlock]
template = "\talways @({{#sensitivity}}{{.}}{{!@last}} or {{/@last}}{{/sensitivity}}) begin\n{{ body }}\tend"

[SensitivityList]
template = "{{ first }}{{#rest}} {{.}}{{/rest}}"

[EdgeSense]
template = "{{ edge }} {{ signal }}"