[PrimaryExpr]
template = "{{ value }}"

[Number]
template = "{{ value }}"

[BitWidthLiteral]
template = "{{ value }}"

[Identifier]
template = "{{ content }}"

[ParenthesizedExpr]
template = "({{ expr }})"

[UnaryOp]
template = "{{ op }}{{ operand }}"

[BinaryOp]
template = "{{ left }} {{ op }} {{ right }}"

[ComparisonExpr]
template = "{{ left }} {{ op }} {{ right }}"

[Expression]
template = "{{ expr }}"

[MulOp]
template = "{{ op }}"

[AddOp]
template = "{{ op }}"

[CmpOp]
template = "{{ op }}"
