[PrimaryExpr]
template = "{{ value }}"

[Number]
template = "{{ value }}"

[BitWidthLiteral]
template = "{{ value }}"

[Identifier]
template = "{{ content }}"

[IndexedId]
template = "{{ id_name }}[{{ index }}]"

[ParenthesizedExpr]
template = "({{ expr }})"

[UnaryOp]
template = "{{ op }}{{ operand }}"

[BinaryOp]
template = "{{ left }} {{ op }} {{ right }}"

[ComparisonExpr]
template = "{{ left }} {{ op }} {{ right }}"

[ConcatExpr]
template = "{{{#items}}{{.}}{{!@last}},{{/@last}}{{/items}}}"

[ReplicateExpr]
template = "{{{ count }}{{ value }}}"

[Expression]
template = "{{ expr }}"

[MulOp]
template = "{{ op }}"

[AddOp]
template = "{{ op }}"

[CmpOp]
template = "{{ op }}"

[LogicAndOp]
template = " && "

[LogicOrOp]
template = " || "
