"""调试：追踪 _parse_module 和 _split_body"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from formatter.verilog_formatter import VerilogFormatter

raw_cg = """// Generated by PyV Compiler

module led_blinker # (parameter CLK_MHZ = 100 , parameter MAX_CNT = 32'd1000 ) (
    
    input wire clk , input wire rst_n , output reg led  
);
\t\treg [31:0] counter;
\talways @(posedge clk or negedge rst_n ) begin
\tif (!rst_n) begin
\t\tcounter <= 32'd0;
\t\tled <= 1'b0;
\tend
\telse if (counter == MAX_CNT) begin
\t\tcounter <= 32'd0;
\t\tled <= ~led;
\tend
\telse begin
\t\tcounter <= counter + 32'd1;
\tend
\tend

endmodule
"""

lines = raw_cg.split('\n')
print(f"Total lines: {len(lines)}")
for i, line in enumerate(lines):
    print(f"  [{i:2d}] {repr(line)}")

fmt = VerilogFormatter()
info = fmt._parse_module(lines)
if info:
    name, params, ports, body = info
    print(f"\nModule: {name}")
    print(f"Params: {params}")
    print(f"Ports: {ports}")
    print(f"Body ({len(body)} lines):")
    for i, line in enumerate(body):
        print(f"  [{i:2d}] {repr(line)}")
    
    decls, always = fmt._split_body(body)
    print(f"\nDeclarations ({len(decls)}):")
    for d in decls:
        print(f"  {repr(d)}")
    print(f"Always blocks ({len(always)}):")
    for j, blk in enumerate(always):
        print(f"  Block {j} ({len(blk)} lines):")
        for i, l in enumerate(blk):
            print(f"    [{i:2d}] {repr(l)}")
    
    print("\nFormatted always blocks:")
    formatted = fmt._format_always_blocks(always)
    for l in formatted:
        print(f"  {repr(l)}")
